/**
 * All user-facing copy lives here.
 *
 * English only for now (Section 9 forbids building i18n infrastructure), but
 * keeping strings out of JSX means a future extraction is a mechanical
 * change rather than an archaeology exercise.
 */
export const strings = {
  brand: {
    name: "FleetBeat",
    tagline: "The live pulse of your fleet.",
  },
  login: {
    title: "Sign in to FleetBeat",
    subtitle: "Fleet operations console",
    emailLabel: "Work email",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    noSignup:
      "FleetBeat accounts are created by our team during onboarding. If you need access, contact your fleet administrator.",
    genericError: "We could not sign you in. Please check your details.",
  },
  activate: {
    title: "Set your password",
    subtitle:
      "Choose a password for your FleetBeat account. This link can only be used once.",
    passwordLabel: "New password",
    confirmLabel: "Confirm password",
    submit: "Set password and continue",
    submitting: "Setting your password…",
    mismatch: "Those passwords do not match.",
    requirements:
      "At least 12 characters, with upper and lower case letters and a number.",
    missingToken:
      "This activation link is incomplete. Ask your FleetBeat contact to re-issue it.",
    success: "Your password is set. You can sign in now.",
  },
  nav: {
    liveTracking: "Live Tracking",
    history: "Trip History",
    zones: "Zones & Places",
    tasks: "Tasks",
    vehicles: "Vehicles",
    drivers: "Drivers",
    maintenance: "Maintenance",
    fuel: "Fuel & Energy",
    compliance: "Compliance",
    analytics: "Analytics",
    safety: "Safety & Rewards",
    reports: "Reports & AI",
    audit: "Audit Log",
    security: "Security",
    settings: "Settings",
    signOut: "Sign out",
  },
  dashboard: {
    liveTitle: "Live Tracking",
    liveSubtitle: "Every vehicle, in real time.",
    comingInPhase2:
      "The live map, vehicle sidebar, KPI strip and alerts feed arrive in Phase 2, once the device inventory and GPS simulation engine are in place.",
    vehiclesTitle: "Vehicles",
    driversTitle: "Drivers",
    notTracked: "Not tracked",
    notTrackedHint:
      "This vehicle has no active GPS device yet. FleetBeat provisions and links devices for you.",
  },
  platform: {
    title: "Platform Admin Console",
    subtitle: "FleetBeat internal — all organizations",
    organizations: "Organizations",
    newOrganization: "New organization",
    devices: "Devices",
    auditLog: "Audit log",
    provisionTitle: "Provision a new organization",
    provisionIntro:
      "This creates the customer's organization and its first administrator. The activation link is shown once here — copy it and send it to them.",
    activationReady: "Organization created",
    activationHint:
      "Copy this one-time link and send it to the new administrator. It is not emailed automatically.",
    copyLink: "Copy link",
    copied: "Copied",
    impersonate: "Open as customer",
    impersonateWarning:
      "You are viewing this account as its administrator. Every impersonation is recorded in the audit log.",
    suspend: "Suspend",
    reactivate: "Reactivate",
  },
  live: {
    filters: {
      all: "All",
      moving: "Moving",
      stopped: "Stopped",
      alert: "Has alert",
      notTracked: "Not tracked",
    },
    searchPlaceholder: "Search vehicle, plate or driver",
    kpiActive: "Active now",
    kpiAlerts: "Active alerts",
    kpiNotTracked: "Not tracked",
    kpiDistance: "Distance today",
    notTrackedNudge: "No GPS device fitted yet",
    layers: "Layers",
    layerVehicles: "Vehicles",
    layerGeofences: "Geofences",
    layerPois: "Points of interest",
    layerClosures: "Road closures",
    flagClosure: "Flag closure",
    closurePrompt:
      "What is closed? Vehicles routed through this point will be flagged for rerouting.",
    layerWeather: "Weather",
    layerTasks: "Task destinations",
    drawGeofence: "Draw geofence",
    drawPolygon: "Polygon",
    drawCircle: "Circle",
    addPoi: "Add POI",
    alertsFeed: "Alerts",
    noAlerts: "No active alerts. Everything looks healthy.",
    connectionLive: "Live",
    connectionReconnecting: "Reconnecting\u2026",
    connectionOffline: "Offline \u2014 showing last known positions",
    stoppedSince: "Stopped since",
    lastSeen: "Last signal",
    noDevice: "No device fitted. FleetBeat provisions and links GPS hardware.",
    acknowledge: "Acknowledge",
    acknowledged: "Acknowledged",
    liftClosure: "Lift",
    resolve: "Resolve",
  },
  tasks: {
    title: "Task Manager",
    subtitle: "Assign jobs to drivers and follow them to completion.",
    newTask: "New task",
    columns: {
      assigned: "Assigned",
      accepted: "Accepted",
      en_route: "En route",
      completed: "Completed",
    },
    cancelled: "Cancelled",
    noTasks: "Nothing here.",
    destination: "Destination",
    pickOnMap: "Click the map to set the destination",
    routePreview: "Route preview",
    previewRoute: "Preview route",
    reassign: "Reassign",
    cancel: "Cancel task",
    complete: "Mark complete",
    unassigned: "Unassigned",
    due: "Due",
    eta: "ETA",
    routingUnavailable:
      "The routing engine is not reachable, so no ETA is shown. The task can still be assigned.",
  },
  history: {
    title: "Trip History",
    subtitle: "Replay a completed trip.",
    selectVehicle: "Vehicle",
    selectDate: "Date",
    noTrips: "No trips recorded for that vehicle and date.",
    play: "Play",
    pause: "Pause",
    speed: "Speed",
    start: "Start",
    end: "End",
  },
  analytics: {
    title: "Analytics",
    subtitle: "Cost, utilisation and emissions across the fleet.",
    trends: "Trends",
    distance: "Distance",
    cost: "Cost",
    emissions: "CO\u2082",
    violations: "Driving violations",
    evTitle: "EV transition candidates",
    evEmpty:
      "No vehicles have enough driving history yet to judge. Candidates appear once a vehicle has three weeks of trips.",
    assetsTitle: "Asset lifecycle",
    anomaliesTitle: "Anomalies",
    anomaliesEmpty: "Nothing unusual in fuel or idle patterns.",
    forecastTitle: "Maintenance forecast",
    forecastEmpty: "No services projected to fall due in the next 30 days.",
  },
  safety: {
    title: "Driver Safety & Rewards",
    subtitle: "Scores, fatigue risk and the monthly leaderboard.",
    leaderboard: "Leaderboard",
    scores: "Driver scores",
    recompute: "Recompute now",
    fatigue: "Fatigue risk",
    points: "Points",
    badges: "Badges",
    leaderboardHiddenNote:
      "Drivers cannot see each other's standings. Turn on peer visibility in Settings if you want them to.",
    leaderboardShownNote: "Drivers can see this leaderboard in the mobile app.",
  },
  assistant: {
    title: "Fleet Assistant",
    open: "Ask the assistant",
    close: "Close assistant",
    placeholder: "Ask about your fleet…",
    send: "Send",
    thinking: "Thinking…",
    intro:
      "Ask about vehicles, drivers, tasks, costs or safety. I can also prepare a change - but nothing happens until you confirm it.",
    offlineNote:
      "Answering without the language model - no ANTHROPIC_API_KEY is configured, so this is the built-in keyword router. The data is live either way.",
    confirmTitle: "Confirm before anything changes",
    confirmHint:
      "Nothing has changed yet. Review what this will do, then confirm.",
    confirm: "Confirm and apply",
    discard: "Discard",
    applied: "Done",
    affected: "This will affect",
    expires: "Expires",
    failed: "The assistant could not answer that. Try rephrasing it.",
    confirmFailed: "That action could not be applied.",
    adminOnly:
      "Only an organisation admin can apply this. Ask an admin to confirm it.",
  },
  copilot: {
    title: "Copilot",
    subtitle: "Suggestions from the live signals. You decide.",
    empty: "Nothing needs your attention right now.",
    run: "Re-analyse",
    running: "Analysing…",
    apply: "Apply",
    dismiss: "Dismiss",
    confirmApply: "Apply this suggestion?",
    confirmApplyHint:
      "This changes real data. Nothing has happened yet - confirm to go ahead.",
    benefit: "Expected benefit",
    informational: "For your awareness - there is nothing to apply.",
    applied: "Applied",
    failed: "That suggestion could not be applied.",
    adminOnly: "Only an organisation admin can apply a suggestion.",
  },
  reports: {
    title: "Reports & AI",
    subtitle:
      "Narrative summaries, maintenance windows and exports. Every proposed change waits for you.",
    summariesTitle: "Fleet summaries",
    summariesEmpty: "No summaries yet. Generate one for this period.",
    generate: "Generate summary",
    generating: "Generating…",
    weekly: "Weekly",
    monthly: "Monthly",
    exportsTitle: "Exports",
    exportsHint: "The cost report for the selected window.",
    exportCsv: "Download CSV",
    exportPdf: "Download PDF",
    exportFailed: "That export could not be downloaded.",
    windowsTitle: "Maintenance windows",
    windowsHint:
      "The quietest day inside each service's due window. These are proposals - booking happens only when you enable auto-booking in Settings, or apply the matching Copilot card.",
    windowsEmpty: "No services are close enough to due to need a window yet.",
    windowsRun: "Propose windows",
    autoBooked: "Booked automatically",
    proposalOnly: "Proposal only",
    tasksThatDay: "tasks that day",
    generatedBy: "Generated by",
  },
  audit: {
    title: "Audit Log",
    subtitle:
      "Every change made in your organisation, and who made it. Entries can never be edited or removed.",
    platformTitle: "Platform Audit Log",
    platformSubtitle:
      "Every action across every organisation, including platform-level events.",
    empty: "No entries match those filters.",
    when: "When",
    who: "Who",
    action: "Action",
    what: "What changed",
    organization: "Organisation",
    platformLevel: "Platform",
    system: "System",
    impersonated: "Impersonated",
    showChanges: "Show changes",
    hideChanges: "Hide changes",
    filterAction: "Action",
    filterActor: "Email contains",
    filterOrg: "Organisation",
    allActions: "All actions",
    allOrgs: "All organisations",
    clear: "Clear filters",
    older: "Older",
    newer: "Newer",
    showing: "Showing",
  },
  security: {
    title: "Security",
    subtitle: "Sign-in activity and the devices your people use.",
    suspicious7d: "Suspicious sign-ins (7d)",
    failed7d: "Failed sign-ins (7d)",
    lockedAccounts: "Locked accounts",
    noKnownDevice: "Users with no known device",
    activityTitle: "Sign-in attempts",
    suspiciousOnly: "Suspicious only",
    devicesTitle: "Known devices",
    devicesEmpty: "No devices recorded yet.",
    devicesHint:
      "A sign-in from a device we have not seen before is flagged and raises an alert.",
    succeeded: "Succeeded",
    failed: "Failed",
    flagged: "Flagged",
    lastSeen: "Last seen",
    activityEmpty: "No sign-in attempts recorded.",
    lockoutNote:
      "An account locks itself after five consecutive failures and unlocks when the lockout expires.",
  },
  settings: {
    title: "Settings",
    subtitle: "How FleetBeat behaves for your organisation, and who can use it.",
    adminOnly: "Only an organisation admin can change these settings.",
    saved: "Saved.",
    saveFailed: "We could not save that.",
    save: "Save changes",
    saving: "Saving…",
    reset: "Reset to defaults",

    profileTitle: "Organisation",
    profileHint: "Shown across the console and on exported reports.",
    name: "Name",
    industry: "Industry",
    timezone: "Time zone",
    contactName: "Main contact",
    contactEmail: "Contact email",
    contactPhone: "Contact phone",

    unitsTitle: "Units and currency",
    distanceUnit: "Distance",
    currency: "Currency",
    km: "Kilometres",
    mi: "Miles",

    pointsTitle: "Driver points",
    pointsHint:
      "What each event is worth. These are your numbers, not ours - the defaults below are only a starting point, and scoring reads whatever you set here.",
    baseline: "Monthly starting balance",
    penalties: "Penalties",
    rewards: "Rewards",
    leaderboardVisible: "Let drivers see the leaderboard",
    leaderboardHint:
      "Off by default. When off, a driver sees only their own score and points in the mobile app.",

    thresholdsTitle: "Alert thresholds",
    thresholdsHint:
      "When the alerts engine raises each kind of alert, for this organisation only.",

    emissionsTitle: "CO₂ emission factors",
    emissionsHint:
      "Kilograms of CO₂ per litre burned, by fuel type. Sustainability reporting uses these figures.",

    autoBookTitle: "Maintenance auto-booking",
    autoBookLabel: "Let the Maintenance Copilot book work orders by itself",
    autoBookHint:
      "Off by default. Leave it off and the Copilot only proposes a service window, which you apply yourself. Turning it on is a standing instruction to book - an auto-created work order commits real money, so it is the one place FleetBeat acts without asking each time.",
    autoBookOn: "On - the Copilot books the window it picks",
    autoBookOff: "Off - the Copilot proposes, you decide",

    teamTitle: "Team",
    teamHint:
      "Dispatchers use this console; drivers use the mobile app and cannot sign in here.",
    inviteTitle: "Invite someone",
    inviteEmail: "Work email",
    inviteName: "Full name",
    inviteRole: "Role",
    invite: "Send invite",
    inviting: "Inviting…",
    inviteDone:
      "Invited. There is no email provider yet, so send them this one-time link yourself:",
    copy: "Copy link",
    copied: "Copied",
    suspend: "Suspend",
    reactivate: "Reactivate",
    teamEmpty: "No one else has been invited yet.",
    noDeviceRole:
      "GPS devices are fitted and removed by FleetBeat staff, not from here.",
  },
  changePassword: {
    title: "Change your password",
    forcedTitle: "Set your own password",
    subtitle: "You will be signed out of every device afterwards.",
    forcedSubtitle:
      "The password you signed in with was issued for first use only. Choose your own before you carry on - nothing else will work until you do.",
    current: "Current password",
    new: "New password",
    confirm: "Confirm new password",
    submit: "Change password",
    submitting: "Changing…",
    mismatch: "Those two passwords do not match.",
    tooShort: "Use at least 12 characters.",
    sameAsCurrent: "Choose a password you have not used here before.",
    success: "Password changed. Sign in again with the new one.",
    failed: "We could not change your password.",
    link: "Change password",
  },
  common: {
    loading: "Loading…",
    retry: "Try again",
    cancel: "Cancel",
    save: "Save",
    search: "Search",
    empty: "Nothing here yet.",
    signedInAs: "Signed in as",
  },
} as const;
