/**
 * All user-facing copy lives here.
 *
 * English only for now (Section 9 forbids building i18n infrastructure), but
 * keeping strings out of JSX means a future extraction is a mechanical
 * change rather than an archaeology exercise.
 */
export const strings = {
  brand: {
    name: "FleetBeat",
    tagline: "The live pulse of your fleet.",
  },
  login: {
    title: "Sign in to FleetBeat",
    subtitle: "Fleet operations console",
    emailLabel: "Work email",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    noSignup:
      "FleetBeat accounts are created by our team during onboarding. If you need access, contact your fleet administrator.",
    genericError: "We could not sign you in. Please check your details.",
  },
  activate: {
    title: "Set your password",
    subtitle:
      "Choose a password for your FleetBeat account. This link can only be used once.",
    passwordLabel: "New password",
    confirmLabel: "Confirm password",
    submit: "Set password and continue",
    submitting: "Setting your password…",
    mismatch: "Those passwords do not match.",
    requirements:
      "At least 12 characters, with upper and lower case letters and a number.",
    missingToken:
      "This activation link is incomplete. Ask your FleetBeat contact to re-issue it.",
    success: "Your password is set. You can sign in now.",
  },
  nav: {
    liveTracking: "Live Tracking",
    history: "Trip History",
    zones: "Zones & Places",
    tasks: "Tasks",
    vehicles: "Vehicles",
    drivers: "Drivers",
    maintenance: "Maintenance",
    fuel: "Fuel & Energy",
    compliance: "Compliance",
    analytics: "Analytics",
    safety: "Safety & Rewards",
    settings: "Settings",
    signOut: "Sign out",
  },
  dashboard: {
    liveTitle: "Live Tracking",
    liveSubtitle: "Every vehicle, in real time.",
    comingInPhase2:
      "The live map, vehicle sidebar, KPI strip and alerts feed arrive in Phase 2, once the device inventory and GPS simulation engine are in place.",
    vehiclesTitle: "Vehicles",
    driversTitle: "Drivers",
    notTracked: "Not tracked",
    notTrackedHint:
      "This vehicle has no active GPS device yet. FleetBeat provisions and links devices for you.",
  },
  platform: {
    title: "Platform Admin Console",
    subtitle: "FleetBeat internal — all organizations",
    organizations: "Organizations",
    newOrganization: "New organization",
    devices: "Devices",
    auditLog: "Audit log",
    provisionTitle: "Provision a new organization",
    provisionIntro:
      "This creates the customer's organization and its first administrator. The activation link is shown once here — copy it and send it to them.",
    activationReady: "Organization created",
    activationHint:
      "Copy this one-time link and send it to the new administrator. It is not emailed automatically.",
    copyLink: "Copy link",
    copied: "Copied",
    impersonate: "Open as customer",
    impersonateWarning:
      "You are viewing this account as its administrator. Every impersonation is recorded in the audit log.",
    suspend: "Suspend",
    reactivate: "Reactivate",
  },
  live: {
    filters: {
      all: "All",
      moving: "Moving",
      stopped: "Stopped",
      alert: "Has alert",
      notTracked: "Not tracked",
    },
    searchPlaceholder: "Search vehicle, plate or driver",
    kpiActive: "Active now",
    kpiAlerts: "Active alerts",
    kpiNotTracked: "Not tracked",
    kpiDistance: "Distance today",
    notTrackedNudge: "No GPS device fitted yet",
    layers: "Layers",
    layerVehicles: "Vehicles",
    layerGeofences: "Geofences",
    layerPois: "Points of interest",
    layerWeather: "Weather",
    layerTasks: "Task destinations",
    drawGeofence: "Draw geofence",
    drawPolygon: "Polygon",
    drawCircle: "Circle",
    addPoi: "Add POI",
    alertsFeed: "Alerts",
    noAlerts: "No active alerts. Everything looks healthy.",
    connectionLive: "Live",
    connectionReconnecting: "Reconnecting\u2026",
    connectionOffline: "Offline \u2014 showing last known positions",
    stoppedSince: "Stopped since",
    lastSeen: "Last signal",
    noDevice: "No device fitted. FleetBeat provisions and links GPS hardware.",
    acknowledge: "Acknowledge",
    resolve: "Resolve",
  },
  tasks: {
    title: "Task Manager",
    subtitle: "Assign jobs to drivers and follow them to completion.",
    newTask: "New task",
    columns: {
      assigned: "Assigned",
      accepted: "Accepted",
      en_route: "En route",
      completed: "Completed",
    },
    cancelled: "Cancelled",
    noTasks: "Nothing here.",
    destination: "Destination",
    pickOnMap: "Click the map to set the destination",
    routePreview: "Route preview",
    previewRoute: "Preview route",
    reassign: "Reassign",
    cancel: "Cancel task",
    complete: "Mark complete",
    unassigned: "Unassigned",
    due: "Due",
    eta: "ETA",
    routingUnavailable:
      "The routing engine is not reachable, so no ETA is shown. The task can still be assigned.",
  },
  history: {
    title: "Trip History",
    subtitle: "Replay a completed trip.",
    selectVehicle: "Vehicle",
    selectDate: "Date",
    noTrips: "No trips recorded for that vehicle and date.",
    play: "Play",
    pause: "Pause",
    speed: "Speed",
    start: "Start",
    end: "End",
  },
  analytics: {
    title: "Analytics",
    subtitle: "Cost, utilisation and emissions across the fleet.",
    trends: "Trends",
    distance: "Distance",
    cost: "Cost",
    emissions: "CO\u2082",
    violations: "Driving violations",
    evTitle: "EV transition candidates",
    evEmpty:
      "No vehicles have enough driving history yet to judge. Candidates appear once a vehicle has three weeks of trips.",
    assetsTitle: "Asset lifecycle",
    anomaliesTitle: "Anomalies",
    anomaliesEmpty: "Nothing unusual in fuel or idle patterns.",
    forecastTitle: "Maintenance forecast",
    forecastEmpty: "No services projected to fall due in the next 30 days.",
  },
  safety: {
    title: "Driver Safety & Rewards",
    subtitle: "Scores, fatigue risk and the monthly leaderboard.",
    leaderboard: "Leaderboard",
    scores: "Driver scores",
    recompute: "Recompute now",
    fatigue: "Fatigue risk",
    points: "Points",
    badges: "Badges",
    leaderboardHiddenNote:
      "Drivers cannot see each other's standings. Turn on peer visibility in Settings if you want them to.",
    leaderboardShownNote: "Drivers can see this leaderboard in the mobile app.",
  },
  common: {
    loading: "Loading…",
    retry: "Try again",
    cancel: "Cancel",
    save: "Save",
    search: "Search",
    empty: "Nothing here yet.",
    signedInAs: "Signed in as",
  },
} as const;
