"""CSV and PDF export (Section 4 item 13).

CSV is generated with the standard library. PDF is generated directly rather
than through a rendering library: the reports here are tabular, a minimal
PDF writer is a few dozen lines, and it keeps the container free of a heavy
dependency whose only job would be to draw the same table.
"""

from __future__ import annotations

import csv
import io
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any


def utcnow() -> datetime:
    return datetime.now(UTC)


def to_csv(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(headers)
    for row in rows:
        writer.writerow(["" if value is None else value for value in row])
    return buffer.getvalue()


# --- Minimal PDF writer -----------------------------------------------------
#
# Enough of the PDF spec to lay out a titled table in Helvetica. Everything
# is drawn as text at explicit coordinates, so there is no font embedding and
# no external dependency.

PAGE_WIDTH = 595  # A4 at 72dpi
PAGE_HEIGHT = 842
MARGIN = 40
LINE_HEIGHT = 14
ROWS_PER_PAGE = 46


def _escape(text: str) -> str:
    return (
        str(text)
        .replace("\\", r"\\")
        .replace("(", r"\(")
        .replace(")", r"\)")
        # Anything outside Latin-1 cannot be shown in the base font; a visible
        # placeholder beats a corrupt file.
        .encode("latin-1", "replace")
        .decode("latin-1")
    )


def _text_op(x: int, y: int, size: int, text: str, bold: bool = False) -> str:
    font = "/F2" if bold else "/F1"
    return f"BT {font} {size} Tf {x} {y} Td ({_escape(text)}) Tj ET\n"


def to_pdf(
    *,
    title: str,
    subtitle: str,
    headers: Sequence[str],
    rows: Sequence[Sequence[Any]],
    column_widths: Sequence[int] | None = None,
) -> bytes:
    """Render a titled table as a PDF document."""
    widths = list(column_widths or [])
    if len(widths) != len(headers):
        usable = PAGE_WIDTH - 2 * MARGIN
        widths = [usable // max(1, len(headers))] * len(headers)

    pages: list[str] = []
    chunk_size = ROWS_PER_PAGE
    chunks = [
        rows[index : index + chunk_size] for index in range(0, len(rows), chunk_size)
    ] or [[]]

    for page_index, chunk in enumerate(chunks):
        content = ""
        y = PAGE_HEIGHT - MARGIN

        if page_index == 0:
            content += _text_op(MARGIN, y, 16, title, bold=True)
            y -= 20
            content += _text_op(MARGIN, y, 9, subtitle)
            y -= 24
        else:
            content += _text_op(MARGIN, y, 10, f"{title} (continued)", bold=True)
            y -= 20

        x = MARGIN
        for header, width in zip(headers, widths, strict=False):
            content += _text_op(x, y, 9, str(header).upper(), bold=True)
            x += width
        y -= 4
        content += f"{MARGIN} {y} m {PAGE_WIDTH - MARGIN} {y} l S\n"
        y -= LINE_HEIGHT

        for row in chunk:
            x = MARGIN
            for value, width in zip(row, widths, strict=False):
                text = "" if value is None else str(value)
                # Truncate rather than overlap the next column.
                limit = max(4, width // 5)
                if len(text) > limit:
                    text = text[: limit - 1] + "…"
                content += _text_op(x, y, 9, text)
                x += width
            y -= LINE_HEIGHT

        footer = f"Generated by FleetBeat on {utcnow():%Y-%m-%d %H:%M UTC}"
        content += _text_op(MARGIN, MARGIN - 10, 7, footer)
        content += _text_op(
            PAGE_WIDTH - MARGIN - 60, MARGIN - 10, 7, f"Page {page_index + 1}"
        )
        pages.append(content)

    return _assemble(pages)


def _assemble(page_contents: list[str]) -> bytes:
    objects: list[bytes] = []

    def add(body: str) -> int:
        objects.append(body.encode("latin-1"))
        return len(objects)

    font_regular = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    font_bold = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

    page_ids: list[int] = []
    content_ids: list[int] = []
    for content in page_contents:
        length = len(content.encode("latin-1"))
        content_ids.append(
            add(f"<< /Length {length} >>\nstream\n{content}endstream")
        )
        page_ids.append(0)  # placeholder, filled below

    pages_id = len(objects) + len(page_contents) + 1

    for index, content_id in enumerate(content_ids):
        page_ids[index] = add(
            f"<< /Type /Page /Parent {pages_id} 0 R "
            f"/MediaBox [0 0 {PAGE_WIDTH} {PAGE_HEIGHT}] "
            f"/Resources << /Font << /F1 {font_regular} 0 R /F2 {font_bold} 0 R >> >> "
            f"/Contents {content_id} 0 R >>"
        )

    kids = " ".join(f"{page_id} 0 R" for page_id in page_ids)
    actual_pages_id = add(
        f"<< /Type /Pages /Kids [{kids}] /Count {len(page_ids)} >>"
    )
    catalog_id = add(f"<< /Type /Catalog /Pages {actual_pages_id} 0 R >>")

    # Fix up the parent reference now that the real id is known.
    for page_id in page_ids:
        objects[page_id - 1] = (
            objects[page_id - 1]
            .decode("latin-1")
            .replace(f"/Parent {pages_id} 0 R", f"/Parent {actual_pages_id} 0 R")
            .encode("latin-1")
        )

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{index} 0 obj\n".encode("latin-1") + body + b"\nendobj\n"

    xref_offset = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode("latin-1")
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += f"{offset:010d} 00000 n \n".encode("latin-1")
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root {catalog_id} 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF\n"
    ).encode("latin-1")
    return bytes(out)
